version: '3'
services:
  scraper-container:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
    cap_add:
      - SYS_ADMIN
